name: Build fosscord client docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
        runs-on: self-hosted
      -
        name: Set up QEMU
        runs-on: self-hosted
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        runs-on: self-hosted
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        runs-on: self-hosted
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        runs-on: self-hosted
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:fosscord-client/"
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: Dockerfile
          push: true
          tags: casraw/fosscord-client:latest